// ==========================
// Allen Spelling Bee — banks.js  (Week 1–11)
// ==========================
const BANKS = {
  "1": [
    { word: "supper", meaning: "晚餐" },
    { word: "circle", meaning: "圓形" },
    { word: "camera", meaning: "相機" },
    { word: "herd", meaning: "畜群" },
    { word: "river", meaning: "河流" },
    { word: "curved", meaning: "彎曲的" },
    { word: "sharp", meaning: "鋒利的" },
    { word: "barber", meaning: "理髮師" },
    { word: "turtle", meaning: "烏龜" },
    { word: "harp", meaning: "豎琴" },
    { word: "purse", meaning: "錢包" },
    { word: "hurt", meaning: "受傷" },
    { word: "burst", meaning: "爆裂" },
    { word: "before", meaning: "在…之前" },
    { word: "forest", meaning: "森林" },
    { word: "third", meaning: "第三" },
    { word: "alarm", meaning: "警報；鬧鐘" },
    { word: "person", meaning: "人" },
    { word: "driver", meaning: "司機" },
    { word: "porch", meaning: "門廊" },
    { word: "birthday", meaning: "生日" },
    { word: "carve", meaning: "雕刻" },
    { word: "orange", meaning: "橘子；橙色" },
    { word: "earthworm", meaning: "蚯蚓" },
    { word: "birth", meaning: "出生" },
    { word: "urge", meaning: "催促；衝動" },
    { word: "twirl", meaning: "旋轉" },
    { word: "perfect", meaning: "完美的" },
    { word: "pearl", meaning: "珍珠" },
    { word: "further", meaning: "更遠的；進一步的" },
    { word: "term", meaning: "學期；術語" },
    { word: "worth", meaning: "價值" },
    { word: "purpose", meaning: "目的" },
    { word: "world", meaning: "世界" },
    { word: "fern", meaning: "蕨類植物" },
    { word: "learn", meaning: "學習" },
    { word: "heard", meaning: "聽見（過去式）" },
    { word: "early", meaning: "早的" },
    { word: "word", meaning: "單字" },
    { word: "worst", meaning: "最糟的" },
    { word: "search", meaning: "搜尋" },
    { word: "serve", meaning: "服務" },
    { word: "thirst", meaning: "口渴" },
    { word: "urgent", meaning: "緊急的" },
    { word: "earnest", meaning: "認真的" },
    { word: "cartoon", meaning: "卡通" },
    { word: "character", meaning: "角色；性格" },
    { word: "souvenir", meaning: "紀念品" },
    { word: "research", meaning: "研究" },
    { word: "environment", meaning: "環境" },
    { word: "trust", meaning: "信任" },
    { word: "talent", meaning: "天分" },
    { word: "participate", meaning: "參加" }
  ],

  "2": [
    { word: "mounds", meaning: "小土堆" },
    { word: "tower", meaning: "塔" },
    { word: "oyster", meaning: "牡蠣" },
    { word: "towns", meaning: "城鎮" },
    { word: "poison", meaning: "毒物" },
    { word: "choice", meaning: "選擇" },
    { word: "mountain", meaning: "山" },
    { word: "couch", meaning: "沙發" },
    { word: "bounce", meaning: "彈跳" },
    { word: "howl", meaning: "嚎叫" },
    { word: "allow", meaning: "允許" },
    { word: "outdoor", meaning: "戶外的" },
    { word: "powder", meaning: "粉末" },
    { word: "shower", meaning: "陣雨；淋浴" },
    { word: "enjoyable", meaning: "令人愉快的" }
  ],

  "3": [
    { word: "whistling", meaning: "吹口哨" },
    { word: "skipped", meaning: "略過" },
    { word: "baked", meaning: "烘烤" },
    { word: "planning", meaning: "計畫中" },
    { word: "saving", meaning: "儲蓄中" },
    { word: "hurried", meaning: "匆忙的" },
    { word: "taped", meaning: "錄音；貼上" },
    { word: "used", meaning: "使用" },
    { word: "laughs", meaning: "笑聲" },
    { word: "copies", meaning: "複製品" },
    { word: "enjoys", meaning: "享受" },
    { word: "passes", meaning: "通過" },
    { word: "switches", meaning: "開關" },
    { word: "misses", meaning: "想念" },
    { word: "deeper", meaning: "更深的" },
    { word: "warmer", meaning: "更溫暖的" },
    { word: "brightest", meaning: "最亮的" },
    { word: "tallest", meaning: "最高的" },
    { word: "colder", meaning: "更冷的" },
    { word: "prettiest", meaning: "最漂亮的" }
  ],

  "4": [
    { word: "lunches", meaning: "午餐（複數）" },
    { word: "families", meaning: "家庭（複數）" },
    { word: "stories", meaning: "故事（複數）" },
    { word: "boxes", meaning: "盒子（複數）" },
    { word: "children", meaning: "孩子（複數）" },
    { word: "women", meaning: "女性（複數）" },
    { word: "geese", meaning: "鵝（複數）" },
    { word: "mice", meaning: "老鼠（複數）" },
    { word: "men", meaning: "男人（複數）" },
    { word: "feet", meaning: "腳（複數）" },
    { word: "sheep", meaning: "綿羊" },
    { word: "wolves", meaning: "狼（複數）" }
  ],

  "5": [
    { word: "cat's", meaning: "貓的" },
    { word: "babies'", meaning: "嬰兒們的" },
    { word: "children's", meaning: "孩子們的" },
    { word: "country's", meaning: "國家的" },
    { word: "life", meaning: "生命" },
    { word: "thief", meaning: "小偷" },
    { word: "wife", meaning: "妻子" },
    { word: "selves", meaning: "自己（複數）" },
    { word: "wolf", meaning: "狼" },
    { word: "vacation", meaning: "假期" },
    { word: "champion", meaning: "冠軍" },
    { word: "castle", meaning: "城堡" }
  ],

  "6": [
    { word: "hurried", meaning: "匆忙的" },
    { word: "watches", meaning: "手錶" },
    { word: "skating", meaning: "溜冰" },
    { word: "funnier", meaning: "更有趣的" },
    { word: "puppies", meaning: "小狗們" },
    { word: "foxes", meaning: "狐狸們" },
    { word: "rename", meaning: "重新命名" },
    { word: "retake", meaning: "重考" },
    { word: "reverse", meaning: "相反" },
    { word: "unfinished", meaning: "未完成的" }
  ],

  "7": [
    { word: "homework", meaning: "家庭作業" },
    { word: "windmill", meaning: "風車" },
    { word: "raincoat", meaning: "雨衣" },
    { word: "sidewalk", meaning: "人行道" },
    { word: "toothbrush", meaning: "牙刷" },
    { word: "storyteller", meaning: "說故事的人" },
    { word: "weekend", meaning: "週末" },
    { word: "cookbook", meaning: "食譜" },
    { word: "blueberry", meaning: "藍莓" },
    { word: "fireplace", meaning: "壁爐" },
    { word: "imagination", meaning: "想像力" }
  ],

  "9": [
    { word: "wasn't", meaning: "was not 的縮寫" },
    { word: "let's", meaning: "let us 的縮寫" },
    { word: "won't", meaning: "will not 的縮寫" },
    { word: "he'd", meaning: "he would 的縮寫" },
    { word: "hasn't", meaning: "has not 的縮寫" },
    { word: "we'll", meaning: "we will 的縮寫" }
  ],

  "10": [
    { word: "poll", meaning: "民意調查" },
    { word: "threw", meaning: "投擲（過去式）" },
    { word: "waste", meaning: "浪費" },
    { word: "role", meaning: "角色" },
    { word: "miner", meaning: "礦工" },
    { word: "site", meaning: "地點；網站" },
    { word: "need", meaning: "需要" },
    { word: "principal", meaning: "校長" },
    { word: "principle", meaning: "原則" }
  ],

  "11": [
    { word: "distrust", meaning: "不信任" },
    { word: "pregame", meaning: "賽前的" },
    { word: "disconnect", meaning: "切斷；中斷" },
    { word: "displeased", meaning: "不高興的" },
    { word: "preheat", meaning: "預熱" },
    { word: "postrace", meaning: "賽後的" },
    { word: "unpleasant", meaning: "令人不快的" },
    { word: "misbehaving", meaning: "行為不當" },
    { word: "inexpensive", meaning: "便宜的" },
    { word: "wonderful", meaning: "很棒的" },
    { word: "forgetful", meaning: "健忘的" },
    { word: "useless", meaning: "無用的" },
    { word: "endless", meaning: "無止盡的" },
    { word: "cloudless", meaning: "無雲的" },
    { word: "rusty", meaning: "生鏽的" },
    { word: "quickly", meaning: "很快地" },
    { word: "successful", meaning: "成功的" },
    { word: "assignment", meaning: "作業；任務" },
    { word: "improvement", meaning: "改進；進步" },
    { word: "theory", meaning: "理論" },
    { word: "classmates", meaning: "同學" },
    { word: "facts", meaning: "事實" }
  ]
};
